### ISSUE TITLE
Checking Endianness with CMake will freeze the VM indefinetly

### ISSUE THREAD

**Issue by Semphriss** [vmactions/freebsd-vm#12]
This problem happens only using this action; in a VM on my local computer, this project compiles fine.

-------------------

Script to reproduce:

```yaml
name: test

on: [push]

jobs:
  build-test:
    runs-on: macos-latest
    steps:
      - name: Test FreeBSD
        uses: vmactions/freebsd-vm@v0.1.0
        with:
          envs: 'BUILD_TYPE'
          usesh: true
          prepare: |
            pkg install -y cmake
          run: |
            mkdir test_cmake && cd test_cmake
            echo "project(TEST)" > ./CMakeLists.txt
            echo "cmake_minimum_required(VERSION 3.0)" >> ./CMakeLists.txt
            echo "include(TestBigEndian)" >> ./CMakeLists.txt
            echo "test_big_endian(WORDS_BIGENDIAN)" >> ./CMakeLists.txt
            echo "add_executable(test_freebsd test.c)" >> ./CMakeLists.txt
            echo "#include <stdio.h>" > ./test.c
            echo "int main() { printf(\"Hello, world\\n\"); return 0; }" >> ./test.c
            cmake .
            make
            ./test_freebsd
```

This will execute everything just fine, up to when the CMake command is run.

The output of the CMake command is:

 ```
-- The C compiler identification is Clang 10.0.1
-- The CXX compiler identification is Clang 10.0.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
```

The build stops there and will not print anything more. The worlkflow will freeze there, and will auto-cancel after 6 hours.

The guilty lines in the CMakeLists.txt are those about Endianness. It seems like CMake seaches for the `sys/types.h` files forever, never finding it but never failing either.
