### ISSUE TITLE
ssh_dispatch_run_fatal: Connection to 127.0.0.1 port 2222: message authentication code incorrect

### ISSUE THREAD

**Issue by jonaski** [vmactions/freebsd-vm#28]
I'm getting the following error after everything completes.

```
ssh_dispatch_run_fatal: Connection to 127.0.0.1 port 2222: message authentication code incorrect
rsync: connection unexpectedly closed (276663018 bytes received so far) [receiver]
rsync error: error in rsync protocol data stream (code 12) at /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-54.120.1/rsync/io.c(453) [receiver=2.6.9]
rsync: connection unexpectedly closed (96117 bytes received so far) [generator]
rsync error: unexplained error (code 255) at /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-54.120.1/rsync/io.c(453) [generator=2.6.9]
```

Full log here: https://github.com/strawberrymusicplayer/strawberry/runs/3208862681

workflow:

```
  build-freebsd:
    name: Build FreeBSD
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build FreeBSD
      id: build-freebsd
      uses: vmactions/freebsd-vm@v0.1.4
      with:
        usesh: true
        mem: 4096
        prepare: pkg install -y git cmake pkgconf gettext-tools boost-libs glib gnutls qt5-core qt5-concurrent qt5-network qt5-sql qt5-dbus qt5-gui qt5-widgets qt5-buildtools qt5-linguisttools qt5-qmake qt5-sqldrivers-sqlite3 qt5-testlib sqlite gstreamer1 gstreamer1-plugins chromaprint protobuf protobuf-c taglib libcdio libmtp gdk-pixbuf2 libgpod fftw3 googletest iconv
        run: |
          sed -i'.original' -e 's/set(INCLUDE_GIT_REVISION ON)/set(INCLUDE_GIT_REVISION OFF)/g' cmake/Version.cmake
          cmake -E make_directory build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug
          cmake --build . --config Debug --parallel 4
```
Full file here:

https://github.com/strawberrymusicplayer/strawberry/blob/3a9a8289ba9886f1647582297426b1586c933e8b/.github/workflows/ccpp.yml#L1699
