### ISSUE TITLE
Raise error on command failure

### ISSUE THREAD

**Issue by animetosho** [vmactions/freebsd-vm#72]
Firstly, thanks for building this action!

Is there any way to cause the action to fail if a command in `run` fails?  
This would be useful for identifying test failures; currently everything seems to pass, even if something actually failed.

**Comment by Jihadist** [comment]
Hi @Neilpang, sorry for ping. Is there any solution for this issue?

**Comment by daniel-mohr** [comment]
I'm not a developer here. But I can share my solution:

```yaml
...
  freebsd_test:
    runs-on: ubuntu-22.04
    name: run tests on FreeBSD
    steps:
    - uses: actions/checkout@v4
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        run: |
          set -e -x
...
```

The flag `usesh: true` is documented in the [README.md](https://github.com/vmactions/freebsd-vm/blob/main/README.md) as `The default shell in FreeBSD is csh, if you want to use sh to execute the run script, please set usesh to true.`. This way you can use the [posix set command](https://www.man7.org/linux/man-pages/man1/set.1p.html) or a similar command (I believe [set from sh](https://man.freebsd.org/cgi/man.cgi?sh) -- see section `Argument List Processing`). With the flag `-e` you get your desired behavior 'exit immediately on fail'. The `-x` flag is not necessary, but it will cause an echo of each command immediately before execution -- this helps to find out at which command an error occurred.

**Comment by hartwork** [comment]
CC #99

**Comment by daniel-mohr** [comment]
I'm not sure this is really completely fixed, is it?

@Neilpang with https://github.com/vmactions/base-vm/commit/504ed79572c53aac953ab6976116fb78df8ffedc#diff-d31ce0453051853c17ba2a5225b3d1bfab548e095bab0967d6acfd1b3ce1b35d you added `sh -e` for the `execSSHSH` case. But `execSSH` is still default, isn't it? And therefore no error is triggered even with the default setting (without `usesh: true` in the configuration), right?

**Comment by Neilpang** [comment]
yes, you are rigtht. 
It's only for sh now.

**Comment by daniel-mohr** [comment]
Ah, you mean the following fails:

```yaml
  freebsd-vm_4:
    runs-on: ubuntu-latest
    name: run tests on FreeBSD 4 (usesh true and default)
    steps:
    - uses: actions/checkout@v4
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1.2.0
      with:
        usesh: true
        run: |
          echo "SHELL: $0"
          ps -p $$
          pwd
          whoami
          freebsd-version
          mkdir foo
          mkdir foo
          ls -lah
```

You are right! (cf. [freebsd-vm_4](https://github.com/daniel-mohr/n/actions/runs/14636811294/job/41069726830))

But this means you have to set `usesh: true`. It's not a perfect solution, but at least it's one! 😉 

But I also find it remarkable that the default shell is obviously a `-sh`, i.e. a login shell. And this is not a `csh` as documented in the README.md. (cf. [freebsd-vm_1](https://github.com/daniel-mohr/n/actions/runs/14636811294/job/41069726824))

In comparison, when setting `usesh: true`, there is no login shell but an `sh -e`, i.e. a shell with the `-e` parameter -- i.e. the shell is terminated immediately if a command returns an error. (cf. [freebsd-vm_4](https://github.com/daniel-mohr/n/actions/runs/14636811294/job/41069726830))

Couldn't the default login shell be replaced by `sh -e`?
