### ISSUE TITLE
running code in multiple GitHub steps

### ISSUE THREAD

**Issue by pmqs** [vmactions/freebsd-vm#87]
Is there any way to split the code you want executed on the FreeBSD vm into a number of GitHub steps?

As things stand the log output isn't that easy to navigate, with the output from all commands concatenated into one file.

Having the code split into logical steps makes it easier to see the output related to specific steps and see clearly where a workflow fails.

A quick search for some prior art found this example from  https://github.com/jirutka/setup-alpine, I see they  allow steps to be used by setting the shell to ` alpine.sh {0}` in the individual step.

```
runs-on: ubuntu-latest
steps:
  - uses: jirutka/setup-alpine@v1
    with:
      branch: v3.15

  - run: cat /etc/alpine-release
    shell: alpine.sh {0}
```

Is something like this possible here?
