### ISSUE TITLE
Unable to update repository FreeBSD

### ISSUE THREAD

**Issue by spvkgn** [vmactions/freebsd-vm#89]
```
      - uses: vmactions/freebsd-vm@v1
        with:
          release: '12.4'
          usesh: true
          prepare: pkg install -y pkgconf
```

```
Run vmactions/freebsd-vm@v1
release: 12.4
nat: 
mem: 
cpu: 
Importing VM
Run onBeforeStartVM
Run startVM
Run onStarted in VM
Initialize files in VM
envs:
Run onInitialized in VM
Run 'prepare' in VM
  Running prepare: pkg install -y pkgconf
  
  exec ssh: pkg install -y pkgconf
  /usr/bin/bash /home/runner/work/_actions/vmactions/freebsd-vm/v1/run.sh execSSHSH
  Config file: freebsd-12.4.conf
  Updating FreeBSD repository catalogue...
  pkg: An error occured while fetching package
  pkg: An error occured while fetching package
  repository FreeBSD has no meta file, using default settings
  pkg: An error occured while fetching package
  pkg: An error occured while fetching package
  Unable to update repository FreeBSD
  Error updating repositories!
  Error: The process '/usr/bin/bash' failed with exit code 3
```
