### ISSUE TITLE
arch: aarch64 targets are slow

### ISSUE THREAD

**Issue by HofiOne** [vmactions/freebsd-vm#98]
I tried the following setup (simplified example; the real-life one uses a bit more complex matrix)

```
jobs:
  general:
    strategy:
      matrix:
        release: [ "15.0", "14.2" ]
        arch: [ amd64, aarch64 ]
        runner: [ ubuntu-24.04, ubuntu-24.04-arm ]
        exclude:
          - runner: ubuntu-24.04
            arch: aarch64
          - runner: ubuntu-24.04-arm
            arch: amd64
      fail-fast: false

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Setup the environment
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true

          release: ${{ matrix.release }}
          arch: ${{ matrix.arch }}

      - name: Step 1
        shell: freebsd {0}
        run: |
...
```

This starts correctly 2 jobs

1. An amd64 shell on an amd64 ubuntu-24.04 runner
2. An aarch64 shell on an aarch64 ubuntu-24.04-aarch64 runner

but the second is extremely slow; it seems it does not run natively on aarch64 (probably emulated under amd64)

Sorry if it is still not yet supported (it is not clear to me if this is already implemented or still on the next feature list)
Could you please enlighten me?
Thank you!
